/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Man(props) {
  const { nodes, materials } = useGLTF('./Male_character.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Man_Base_mesh003.geometry}
        material={nodes.Man_Base_mesh003.material}
      />
    </group>
  )
}

useGLTF.preload('./Male_character.glb')
